config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'index#index'
    resources :order, :menu, :charges
    devise_for :users

  end
end

app/models/address.rb
class Address < ApplicationRecord
  has_many :kitchens
  has_many :users

  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Wrong email format" }
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diet_and_allergy.rb
class DietAndAllergy < ApplicationRecord
  has_many :users
  has_many :menus

end

app/models/kitchen.rb
class Kitchen < ApplicationRecord
  belongs_to :address
  has_many :orders
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :diet_and_allergy
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :users
  belongs_to :kitchens
  belongs_to :menus
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  private

  def set_locale
    if params[:locale] == nil
      I18n.locale = http_accept_language.compatible_language_from(I18n.available_locales)
    else
      I18n.locale = params[:locale]
    end
  end


  def default_url_options(options = {})
    { locale: I18n.locale }
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    @amount = 500

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
  
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index

  end

end

app/controllers/menu_controller.rb
class MenuController < ApplicationController

  def index
  end
  def show
  end
  def new
  end
  def create
  end
  def edit
  end
  def update
  end
  def destroy
  end

end

app/controllers/order_controller.rb
class OrderController < ApplicationController

  def index
  end
  def show
  end
  def new
  end
  def create
  end
  def edit
  end
  def update
  end
  def destroy
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/charges/create.html.erb
<div class="paymentSuccess">

<%= flash[:success] = "Le paiement a été accepté." %>

</div>

app/views/charges/new.html.erb
<div class="payment">
  <%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Amount: $5.00</span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="A month's subscription"
            data-amount="500"
            data-locale="auto"></script>
  <% end %>
</div>

app/views/index/index.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <title>Cuisines Collectives Citoyennes</title>
  <meta name="description" content="Cuisines Collectives Citoyennes"
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <div id="content_weare">
    <div class="weare_title">
      <h1>Bienvenues dans vos Cuisines Collectives Citoyennes</h1>
    </div>
    <div class="weare_text">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse condimentum ante ac convallis pellentesque. Nullam sit amet elit viverra, gravida risus in, suscipit purus. Donec viverra massa dolor, sit amet accumsan lacus cursus sed. Aliquam nulla arcu, tempus ut faucibus a, cursus vitae odio. Donec consequat, neque sagittis faucibus maximus, quam elit ultrices ligula, ac sollicitudin dolor urna nec leo. Curabitur vitae augue nisl. Donec leo sapien, venenatis maximus neque eget, efficitur bibendum velit. Aenean et eros in dui finHibus dapibus. Suspendisse sagittis orci iaculis nisi imperdiet euismod. Sed et cursus ante. Aenean condimentum laoreet nibh eget condimentum. Proin ac luctus metus. Curabitur vel egestas risus. Ut imperdiet aliquet varius. Sed mattis malesuada purus quis mattis.<br></p>
      <p>Nam vitae rutrum ante, vitae congue erat. Proin convallis quam nisi, vel pellentesque enim pellentesque eget. Sed sed pretium sapien, scelerisque tincidunt neque. Vivamus sit amet vulputate nunc. Morbi ac libero quis mi scelerisque accumsan id et eros. Pellentesque in orci tellus. Integer et feugiat orci, non iaculis ante. Praesent feugiat leo vel pharetra ullamcorper. Morbi bibendum posuere dui, quis commodo justo finibus vel. Sed nisi ante, tempus at molestie nec, fringilla quis quam. In maximus maximus velit, sit amet hendrerit est imperdiet quis. Aliquam erat volutpat. Nam accumsan massa sed nisl auctor vehicula. Nam ipsum augue, sollicitudin nec auctor eu, dapibus ac mi. Sed tincidunt sem semper auctor tincidunt. Nunc sed interdum felis. <br> </p>
    </div>
  </div>
  <div id="content_artist">
  </div>
  <div class="" id="content_commands">
    <div class="orders_buttons">
      <div class="menu_button">
        <a class="m-4 btn btn-info btn-lg" href="<%= menu_index_path %>"><%= t "buttons.menu.index" %></a>
      </div>
      <div class="new_order_button">
        <a class="m-4 btn btn-danger btn-lg" href="<%= new_order_path %>"><%= t "buttons.order.new" %></a>
      </div>
    </div>
  </div>
</body>
<script type="text/javascript">
// Add the sticky class to the navbar when you reach its scroll position. Remove "sticky" when you leave the scroll position
function myFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky")
  } else {
    navbar.classList.remove("sticky");
  }
}
</script>
</html>

app/views/layouts/_notice.html.erb
<% if flash[:success] %>
  <div class="alert alert-success text-center" role="alert">
    <i class="fa fa-info-circle" aria-hidden="true"></i> <%= flash[:success] %>
  </div>
<% end %>

<!-- Error messages -->
<% if flash[:error] %>
  <div class="alert alert-danger text-center" role="alert">
    <i class="fa fa-info-circle" aria-hidden="true"></i> <%= flash[:error] %>
  </div>
<% end %>

<!-- Notice messages -->
<% if flash[:notice] %>
  <div class="alert alert-info text-center" role="alert">
    <i class="fa fa-info-circle" aria-hidden="true"></i> <%= flash[:notice] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CCube</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('logo1.png') %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <div id="topbar" class="sticky">
      <div class="logo">
        <%= image_tag "logo1.png" %>
      </div>
      <div class="buttons">
        <a href="/#content_weare" style="text-decoration: none" class="weare">
          <div class="weare">
            <p><%= t "nav.about_us"%><p>
          </div>
        </a>
        <a href="/#content_artist" style="text-decoration: none" class="artists">
          <div class="artists">
            <p><%= t "nav.artists"%></p>
          </div>
        </a>
        <a href="/#content_commands" style="text-decoration: none" class="commands">
          <div class="commands">
            <p><%= t "nav.orders"%></p>
          </div>
        </a>
      </div>
      <div class="right_buttons">
        <div class="dropdown change_language">
          <a class="btn btn-secondary dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= I18n.locale %>
          </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <div class="dropdown-item">
              <%= link_to_unless_current "fr", locale: :fr %>
            </div>
            <div class="dropdown-divider"></div>
            <div class="dropdown-item">
              <%= link_to_unless_current "en", locale: :en %>
            </div>
            <div class="dropdown-divider"></div>
            <div class="dropdown-item">
              <%= link_to_unless_current "nl", locale: :nl %>
            </div>
          </div>
        </div>
        <% if user_signed_in? %>
          <div class="dropdown btn btn-secondary log_button"><%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          </div>
        <% else %>
          <a class="btn btn-secondary" href="<%= new_user_session_path %>">Sign in</a>
          <a class="btn btn-secondary" href="<%= new_user_registration_path %>">Sign up</a>
        <% end %>
      </div>
    </div>
    <!-- exemple de fenetre modale de sign in en bootstrap


    <a class="btn btn-secondary" data-toggle="modal" data-target="#modal">Sign in</a>


    <div class="modal-signin modal" id="modal" role="dialog" aria-labelledby="signinLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title text-center" id="signinLabel">Connexion</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body text-center">
            <form class="form-signin" action="traitement.php" method="post">
              <label for="username">Email : </label>
              <input type="text" name="username" value="" required="required">
              <br/>
              <label for="password">Mot de passe : </label>
              <input type="password" name="password" value="" required="required">
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn text-center btn-" id="sendSignin">Valider</button>
          </div>
        </div>
      </div>
    </div>
  -->
  </header>

    <%= yield %>
  </body>
  <footer>

  </footer>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CCube</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('logo1.png') %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <div id="topbar" class="sticky">
      <div class="logo">
        <%= image_tag "logo1.png" %>
      </div>
      <div class="buttons">
        <a href="/#content_weare" style="text-decoration: none" class="weare">
          <div class="weare">
            <p><%= t "nav.about_us"%><p>
          </div>
        </a>
        <a href="/#content_artist" style="text-decoration: none" class="artists">
          <div class="artists">
            <p><%= t "nav.artists"%></p>
          </div>
        </a>
        <a href="/#content_commands" style="text-decoration: none" class="commands">
          <div class="commands">
            <p><%= t "nav.orders"%></p>
          </div>
        </a>
      </div>
      <div class="right_buttons">
        <div class="dropdown change_language">
          <a class="btn btn-secondary dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= I18n.locale %>
          </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <div class="dropdown-item">
              <%= link_to_unless_current "fr", locale: :fr %>
            </div>
            <div class="dropdown-divider"></div>
            <div class="dropdown-item">
              <%= link_to_unless_current "en", locale: :en %>
            </div>
            <div class="dropdown-divider"></div>
            <div class="dropdown-item">
              <%= link_to_unless_current "nl", locale: :nl %>
            </div>
          </div>
        </div>
        <% if user_signed_in? %>
          <div class="dropdown btn btn-secondary log_button"><%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          </div>
        <% else %>
          <a class="btn btn-secondary" href="<%= new_user_session_path %>">Sign in</a>
          <a class="btn btn-secondary" href="<%= new_user_registration_path %>">Sign up</a>
        <% end %>
      </div>
    </div>
    <!-- exemple de fenetre modale de sign in en bootstrap


    <a class="btn btn-secondary" data-toggle="modal" data-target="#modal">Sign in</a>


    <div class="modal-signin modal" id="modal" role="dialog" aria-labelledby="signinLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title text-center" id="signinLabel">Connexion</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body text-center">
            <form class="form-signin" action="traitement.php" method="post">
              <label for="username">Email : </label>
              <input type="text" name="username" value="" required="required">
              <br/>
              <label for="password">Mot de passe : </label>
              <input type="password" name="password" value="" required="required">
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn text-center btn-" id="sendSignin">Valider</button>
          </div>
        </div>
      </div>
    </div>
  -->
  </header>

    <%= yield %>
  </body>
  <footer>

  </footer>
</html>

app/views/menu/new.html.erb
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
</head>
<body>
    <form action="#script-vincent" method="post" >

        <fieldset>
            <legend>Menu</legend>

            <label for="date" >Date du menu : </label>
            <input id="date" type="date" />

            <!-- Sélection repas -->

            <input id="midi" name="repas" type="radio" value="midi" />
            <label for="midi" >Midi</label>

            <input id="soir" name="repas" type="radio" value="soir" />
            <label for="soir" >Soir</label>

            <p>Régime alimentaire :</p>

            <input id="omni" name="regime" type="radio" value="omni" />
            <label for="omni" >Omnivore</label>

            <input id="vege" name="regime" type="radio" value="vege" />
            <label for="vege" >Végétarien</label>

            <input id="vegan" name="regime" type="radio" value="vegan" />
            <label for="vegan" >Végane</label><br/>

            <p>Allergies :</p>

            <input id="arachides" name="allergies" type="checkbox" value="arachides" />
            <label for="arachides" >Arachides</label>

            <input id="oeufs" name="allergies" type="checkbox" value="oeufs" />
            <label for="oeufs" >Œufs</label>

            <input id="gluten" name="allergies" type="checkbox" value="gluten" />
            <label for="gluten" >Gluten</label>

        </fieldset>

        <fieldset>
            <legend>Livraison</legend>

            <label for="heure_livraison" >Heure de livraison souhaitée : </label>
            <input id="heure_livraison" name="heure_livraison" type="time" />

            <p>J'ai un contenant : </p>

            <label for="contenant" >Oui</label>
            <input id="contenant" name="is_contenant" type="radio" value="oui" />

            <label for="pas_contenant" >Non</label>
            <input id="pas_contenant" name="is_contenant" type="radio" value="non" checked />

        </fieldset>

        <fieldset>
            <legend>Adresse</legend>

            <label for="voie" >Voie : </label>
            <input id="voie" name="rue" type="text" /><br/>

            <label for="numero" >Numéro : </label>
            <input id="numero" max="999" min="1" name="numero" size="3" type="number" />

            <label for="boite" >Boite : </label>
            <input id="boite" maxlength ="3" name="boite" size="3" type="text" /><br/>

            <label for="cp" >Code postal : </label>
            <input id="cp" maxlength="4" name="cp" size="4" type="text" /><br/>

        </fieldset>

        <fieldset>
            <legend>Coordonnées</legend>

            <label for="email" >E-mail : </label>
            <input id="email" type="email" />

            <label for="telephone" >Téléphone : </label>
            <input id="telephone" type="tel" >

        </fieldset>

        <fieldset>
            <legend>Paiement</legend>

            <label for="especes" >Espèces</label>
            <input id="especes" name="paiement" type="radio" value="especes" />

            <label for="online" >En ligne</label>
            <input id="online" name="paiement" type="radio" value="online" />

        </fieldset>

    </form>
</body>
</html>

app/views/order/new.html.erb
<body>
  <div class="order_form">
    <form action="#script-vincent" method="post" >

        <fieldset>
            <legend>Menu</legend>

            <label for="date" >Date du menu : </label>
            <input id="date" type="date" />

            <!-- Sélection repas -->

            <input id="midi" name="repas" type="radio" value="midi" />
            <label for="midi" >Midi</label>

            <input id="soir" name="repas" type="radio" value="soir" />
            <label for="soir" >Soir</label>

            <p>Régime alimentaire :</p>

            <input id="omni" name="regime" type="radio" value="omni" />
            <label for="omni" >Omnivore</label>

            <input id="vege" name="regime" type="radio" value="vege" />
            <label for="vege" >Végétarien</label>

            <input id="vegan" name="regime" type="radio" value="vegan" />
            <label for="vegan" >Végane</label><br/>

            <p>Allergies :</p>

            <input id="arachides" name="allergies" type="checkbox" value="arachides" />
            <label for="arachides" >Arachides</label>

            <input id="oeufs" name="allergies" type="checkbox" value="oeufs" />
            <label for="oeufs" >Œufs</label>

            <input id="gluten" name="allergies" type="checkbox" value="gluten" />
            <label for="gluten" >Gluten</label>

        </fieldset>

        <fieldset>
            <legend>Livraison</legend>

            <label for="heure_livraison" >Heure de livraison souhaitée : </label>
            <input id="heure_livraison" name="heure_livraison" type="time" />

            <p>J'ai un contenant : </p>

            <label for="contenant" >Oui</label>
            <input id="contenant" name="is_contenant" type="radio" value="oui" />

            <label for="pas_contenant" >Non</label>
            <input id="pas_contenant" name="is_contenant" type="radio" value="non" checked />

        </fieldset>

        <fieldset>
            <legend>Adresse</legend>

            <label for="voie" >Voie : </label>
            <input id="voie" name="rue" type="text" /><br/>

            <label for="numero" >Numéro : </label>
            <input id="numero" max="999" min="1" name="numero" size="3" type="number" />

            <label for="boite" >Boite : </label>
            <input id="boite" maxlength ="3" name="boite" size="3" type="text" /><br/>

            <label for="cp" >Code postal : </label>
            <input id="cp" maxlength="4" name="cp" size="4" type="text" /><br/>

        </fieldset>

        <fieldset>
            <legend>Coordonnées</legend>

            <label for="email" >E-mail : </label>
            <input id="email" type="email" />

            <label for="telephone" >Téléphone : </label>
            <input id="telephone" type="tel" >

        </fieldset>

        <fieldset>
            <legend>Paiement</legend>

            <label for="especes" >Espèces</label>
            <input id="especes" name="paiement" type="radio" value="especes" />

            <label for="online" >En ligne</label>
            <input id="online" name="paiement" type="radio" value="online" />

        </fieldset>

    </form>

    <%= link_to "Payer", new_charge_path %>
  </div>
</body>
</html>